[package]
cairo-version = "2.12.2"
name = "tournaments"
version = "0.0.1"
edition = "2024_07"

[lib]

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["dojo::world::world_contract::world"]

[dependencies]
dojo = "1.7.0"
dojo_cairo_macros = "1.7.0"
starknet = "2.12.2"
openzeppelin_introspection = "1.0.0"
openzeppelin_token = "1.0.0"

[dev-dependencies]
cairo_test = "=2.12.2"
dojo_cairo_test = "1.7.0"

[features]
default = []

[profile.dev]
[profile.slot]
[profile.sepolia]
[profile.mainnet]