[package]
cairo-version = "2.12.2"
name = "budokan"
version = "0.0.1"
edition = "2024_07"

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "dojo::world::world_contract::world",
    "game_components_test_starknet::minigame::mocks::minigame_starknet_mock::minigame_starknet_mock",
    "game_components_test_starknet::metagame::mocks::metagame_starknet_mock::metagame_starknet_mock",
    "game_components_token::examples::full_token_contract::FullTokenContract",
    "game_components_token::examples::minigame_registry_contract::MinigameRegistryContract",
]

[dependencies]
openzeppelin_introspection = "1.0.0"
openzeppelin_token = "1.0.0"
dojo = "1.7.0"
dojo_cairo_macros = "1.7.0"
starknet = "2.12.2"
game_components_metagame = { git = "https://github.com/dpinones/game-components", branch = "bump-cairo-2.12.2" }
game_components_minigame = { git = "https://github.com/dpinones/game-components", branch = "bump-cairo-2.12.2" }
game_components_utils = { git = "https://github.com/dpinones/game-components", branch = "bump-cairo-2.12.2" }
game_components_test_starknet = { git = "https://github.com/dpinones/game-components", branch = "bump-cairo-2.12.2" }
game_components_token = { git = "https://github.com/dpinones/game-components", branch = "bump-cairo-2.12.2" }

[dev-dependencies]
cairo_test = "=2.12.2"
dojo_cairo_test = "1.7.0"

[profile.dev]
[profile.slot]
[profile.sepolia]
[profile.mainnet]